name: Update from upstream cask definition

on:
  # Run every 4 hours.
  schedule:
    - cron: "0 */4 * * *"

  # Also allow manual triggering.
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout both superproject and submodule.
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set Git committer identity
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions@github.com"

      - uses: mxschmitt/action-tmate@v3

      - name: Update from upstream
        run: make update
